### ISSUE TITLE
References to binstar

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/docs.anaconda.org#105]
Still a lot of references to binstar in the docs:
http://docs.anaconda.org/build-config.html

@electronwill

**Comment by electronwill** [comment]
Good catch. I'll change 'binstar' to 'Anaconda.org' in the text, and add a sentence explaining that Anaconda.org used to be binstar.org. After that I'll list the commands and variables that contain 'binstar', use the conda docs where possible to figure out what they should change to, and follow up with you here about anything that's still unclear.
