### ISSUE TITLE
Couldn't update conda-env

### ISSUE THREAD

**Issue by watsodw** [Anaconda-Server/docs.anaconda.org#106]
Got this error:
Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/anaconda/osx-64/conda-env-2.4.2-py27_0.tar.bz2

**Comment by malev** [comment]
hello @watsodw, looks like you have some updates to do.
* We renamed `binstar.org` into `anaconda.org`.
* We released some new products that you can find helpful.
Can you please try updating conda. Run `conda update conda` and try it again? If you run into more problems please consider writing to the [conda mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/conda).

**Comment by electronwill** [comment]
https://conda.binstar.org/anaconda/osx-64/ does show 'conda-env	2.4.2	py27_0	conda-env-2.4.2-py27_0.tar.bz2', and the link goes to a 404. https://conda.anaconda.org/anaconda/osx-64/ also shows 'conda-env	2.4.2	py27_0	conda-env-2.4.2-py27_0.tar.bz2', and that link is also a 404.

**Comment by malev** [comment]
@electronwill because conda-env lives at the anaconda's repo: http://repo.continuum.io/pkgs/free/osx-64/
