### ISSUE TITLE
There are *NO* healthy workers accepting jobs for the queue build/binstar/public.

### ISSUE THREAD

**Issue by BjornFJohansson** [Anaconda-Server/docs.anaconda.org#107]
Hi, 
I have had no builds for about 24 hours. Is this excpected? Is there a way of telling if there is capacity 
available on Anaconda.org?

thanks!

**Comment by mutirri** [comment]
Hi,

> I have had no builds for about 24 hours.

Sorry for that.

> Is this excpected?

No. 
We have some issues related to anaconda `build-workers`.
However right now both of them are available once again.
Feel free to use them.

> Is there a way of telling if there is capacity available on Anaconda.org?

If you are asking:

a) of space occupied by all of your packages (and your account limits for them), then plase visit below page:
https://anaconda.org/settings/storage
b) but if you are asking of free space on the disk which is available for build process on each `build-worker`, then the answer for now is no.

I have created enhance issue for this request: 
https://github.com/Anaconda-Server/anaconda-build/issues/78

Best.

**Comment by henningpeters** [comment]
The problem seem to be occurring again, currently no builds can be submitted. Please be aware that the error message might be also a bit misleading as it is not 100% clear whether the problem is in the submitter's responsibility or not:

```
There are *NO* healthy workers accepting jobs for the queue build/binstar/public. Your build was not submitted
```

Last successful build according to ```https://anaconda.org/dashboard/builds?queue=build%2Fbinstar%2Fpublic&all=1``` was 16 days ago.
