### ISSUE TITLE
Some docs issues reported on gitter

### ISSUE THREAD

**Issue by asmeurer** [Anaconda-Server/docs.anaconda.org#111]
Reported on the conda/conda gitter:

> http://docs.anaconda.org/examples.html#SubmitYourFirstBuild has: binstar-build init
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!
!!  The 'binstar-build' conda package has been renamed to 'anaconda-build'.
!!  Please run:
!!
!!    conda install anaconda-build
!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

> als dead link on Example conda package on http://docs.binstar.org/build_cli.html

**Comment by malev** [comment]
thanks @asmeurer I believe @electronwill will update this soon

**Comment by electronwill** [comment]
1) At http://docs.anaconda.org/examples.html I understand that binstar-build should be anaconda-build.

1A) Should "conda config --set binstar_upload no" be binstar_upload, anaconda_upload, or something else?

1B) Does "anaconda-build init" add .binstar.yml , .anaconda.yml , or something else?

2) It seems the repository that link pointed to is renamed and the file it pointed to is gone.

2A) Should we replace the file or remove the link?

2B) If we should replace the file, is there a copy of that deleted file on GitHub somewhere?

**Comment by asmeurer** [comment]
`conda config --set binstar_upload` has been renamed to `anaconda_upload` (but `binstar_upload` still works for backwards compatibility).

**Comment by electronwill** [comment]
Thank you!

**Comment by electronwill** [comment]
tested, turns out "anaconda-build init" still names the file it creates .binstar.yml

**Comment by electronwill** [comment]
http://docs.anaconda.org/examples.html now has anaconda-build instead of binstar-build, after https://github.com/Anaconda-Server/docs.anaconda.org/pull/112
