### ISSUE TITLE
When user name is empty, anaconda.org displays "<Undefined>"

### ISSUE THREAD

**Issue by pzwang** [Anaconda-Server/docs.anaconda.org#113]
We should have a nicer-looking placeholder for "No User Name" that doesn't make it look like a template rendering error in our software.  Ideally, it would say something like "No User Name" or be just the same as the user's short name, and be a link to the Profile Settings page.

**Comment by electronwill** [comment]
This needs changing in the code instead of in the docs, so I moved it: https://github.com/Anaconda-Server/anaconda-server/issues/633
