### ISSUE TITLE
BUG: Copied package results in author change

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Server/docs.anaconda.org#114]
So, someone copied my [`openblas`]( https://anaconda.org/jakirkham/openblas ) package, which is great. I'm happy to see it being used by others.

That being said, it resulted in my name being removed as the author on the uploaded files in my channel. Instead, the person, who copied, shows up as the author. This seems incorrect as I built and uploaded the package.

**Comment by goanpeca** [comment]
Thanks for reporting, we have moved the issue to our internal issue tracking system.

**Comment by jakirkham** [comment]
I understand this has been closed here again.

If its just because this was moved to an internal issue tracker, that is fine. However, if this is not the reason, I would like you to be aware that I am still seeing this problem.

**Comment by electronwill** [comment]
Yes, the bug is still active, and has been copied into the internal issue tracker at https://github.com/Anaconda-Server/anaconda-server/issues/612 . I apologize for not saying so when I closed the issue. @srossross should we leave docs.anaconda.org issue #114 open as well, to remind us to reply here when #612 is resolved?

**Comment by electronwill** [comment]
Talked with @srossross and confirmed that we will leave this open and reply here when it's resolved.

**Comment by electronwill** [comment]
Copy functionality is temporarily disabled until it can be relaunched in a future release: https://github.com/Anaconda-Server/docs.anaconda.org/issues/119

**Comment by jakirkham** [comment]
Understood, thanks for the update.

**Comment by stephenakearns** [comment]
related to #119

**Comment by dsludwig** [comment]
This has been fixed in the latest release - the uploader of the file will not change when copied into another package. Thank you for reporting the issue!
