### ISSUE TITLE
Private packages download failure caused by invalid certificate 

### ISSUE THREAD

**Issue by doob-project** [Anaconda-Server/docs.anaconda.org#116]
While downloading private packages from our anaconda account:
> conda update -c https://conda.anaconda.org/t/$TOKEN/my_account PACKAGE

Error: Connection error: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Max retries exceeded with url: "..." (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))): <our_private_anaconda_repository>

Having the same issue while downloading the tar.gz from the browser.

**Comment by electronwill** [comment]
This issue is now on our bug tracking list, and we will reply here when it is resolved.

**Comment by electronwill** [comment]
Our developers think this may have been an intermittent network connection problem. Could you please retry and let us know whether it works? If you get the same error again, we'll escalate the issue and do more testing to track it down.

**Comment by doob-project** [comment]
Hello, thanks for your reply. 
We are having the same error, from the browser and from the command line.

**Comment by electronwill** [comment]
Thank you. Issue is escalated and I will continue to reply here with updates.

**Comment by doob-project** [comment]
Hello, any news about this issue? Thanks.

**Comment by doob-project** [comment]
Hello, is there any news on this issues? 
At the moment the only workaround is to update one package at once, which is very time expensive and not matching our production needs.

**Comment by srossross** [comment]
I am not sure how to reproduce this error in our environments. 

After reading up a bit more on the issue, it looks like it may be a issue with the python `requests` library when s3 sends a 104 return code. 

Boto seems to have created a HttpRequest subclass to fix the issue boto/botocore#303 . We are not using the boto library directly, so I am not sure how to take advantage of that with the type of s3 authentication we are using.  I will follow up with an issue to the requests issue tracker to see if they can better understand the details of what is going on.

Thanks
~Sean

**Comment by srossross** [comment]
I found this on the s3 site

> To configure your application to send the Request Headers prior to sending the request body, use the 100-continue HTTP status code. For POST operations, this helps you avoid sending the message body if the message is rejected based on the headers (e.g., authentication failure or redirect). For more information on the 100-continue HTTP status code, go to Section 8.2.3 of http://www.ietf.org/rfc/rfc2616.txt.

@doob-project can you send me the package you are trying to upload?

**Comment by doob-project** [comment]
Hello srossross, thanks for your reply. 
We are having this issue while downloading package from our private repository at anaconda server, from the commandline and from the browser as well. 

The requested URL looks like this: 
https://binstar-cio-packages-prod.s3.amazonaws.com/<oid>/<oid>?Signature=<value>&Expires=<expires>&AWSAccessKeyId=<aws_key_id>&response-content-disposition=attachment%3B%20filename%3Dwin-64/gsf-2.4-np19py27_675.tar.bz2&response-content-type=application/x-tar&x-amz-security-token=<a_very_long_token>

Since we are trying to access to a private package, I cannot paste here the real url. If this sample doesn't help, I'll send you a private message with the real url.

Thanks in advance for your support.

**Comment by srossross** [comment]
> At the moment the only workaround is to update one package at once, which is very time expensive and not matching our production needs.

@doob-project can you explain this in a bit more detail? What is your workaround?

**Comment by doob-project** [comment]
@srossross basically our web app depends on three different packages wich are built nightly by our CI infrastructure. 
When we have to deploy the new packages in our servers environment we use the command:

`[user@server ~]$ conda update package1 package2 package3`

The .condarc for that enviroment looks like the following:
`channels:`
`    - https://conda.anaconda.org/t/<token>/prometeia/channel/dev`
`    - https://conda.anaconda.org/t/<token>/prometeia`
`    - defaults`
`ssl_verify: false`

After the packages dependencies resolution, the anaconda client starts to download the required packages. All our target packages live in a private channel. 
The download of one of the three packages always fail and stop the update process, so we have to issue the command `conda update package1` until it works, then we have to `conda update package2` until it works, finally the third one `conda update package3`. 
At the moment we have a cluster of three servers and we have to repeat the procedure for each one of them. As you can imagine, there's no fun...

The .condarc ssl_verify option to false was our first attempt to solve the issue.

The server now runs CentOS 6.6, with miniconda python 2.7.10:
anaconda-client: 1.0.2-py27_0
requests:        2.7.0-py27_0

We tried in a local environment with the latest version of these packages with no luck. As I mentioned, we are having the same issue downloading the package with the browser from anaconda.org.

Thanks for your support.

**Comment by srossross** [comment]
@doob-project, I don't still am at a loss as to how to reproduce this. I think a fix will probably be in the new year.

In the mean time to speed up the process:

 1. Are all three packages private? Do you have trouble with those three, or have you had trouble with other packages as well? 
 1. If so, can you check if you get this error with a public package?
 1. When you get this error in the browser, can you send me a screen shot? Possibly a browser log? (To do this with chrome use the [chrome devtools](https://developer.chrome.com/devtools))

**Comment by doob-project** [comment]
@srossross to answer to your questions:

1. Yes, all the three packages are private
2. We aren't able to reproduce this error with a public package.
3. I'm sending you an email with the chrome log

Thanks for your help.
