### ISSUE TITLE
Cannot Sort By Number of Downloads

### ISSUE THREAD

**Issue by saulspatz** [Anaconda-Server/docs.anaconda.org#117]
I'm just trying out conda.  In accordance with the instructions in the 30-minute tour, I went to http://anaconda.org/search?q=bottleneck&sort=_ndownloads&sort_order=1&reverse=true
Clicking on the downloads button doesn't sort by number of downloads.  I see reverse=true and reverse=false toggling in the address bar, but the order of the packages doesn't change at all.

I am using Chrome Version 45.0.2454.93 (64-bit) on Yosemite Version 10.10.5

**Comment by electronwill** [comment]
This issue is now on our bug tracking list, and we will reply here when it is resolved.

**Comment by srossross** [comment]
@malev can you move this to the correct part of the pipeline?

**Comment by stephenakearns** [comment]
I moved it back to the backlog - related to #778 I believe - also assigned to @malev

**Comment by stephenakearns** [comment]
This is being resolved by Anaconda-Server/Anaconda-Server#778

**Comment by rafaelhbarros** [comment]
The issue Anaconda-Server/anaconda-server#778 was closed, should this be moved to closed too?
