### ISSUE TITLE
Package copy command on conda.binstar.org is STILL wrong

### ISSUE THREAD

**Issue by remram44** [Anaconda-Server/docs.anaconda.org#118]
I reported that a long time ago through the website, but heh.

https://conda.binstar.org/

    $ binstar package --copy wakari/flask/0.10 YOU --channel testing
    binstar package: error: one of the arguments --add-collaborator --list-collaborators --create is required

**Comment by remram44** [comment]
Note that using the correct command gives me "Internal server error" so this is just great.

    $ binstar copy --to-owner vida-nyu remram/file_archive/0.6
    Using binstar api site https://api.anaconda.org
    [ServerError] Internal server error

**Comment by srossross** [comment]
@remram44 I am very sorry for the inconvenience.  Our copy functionality seems to be broken. we are actively working on this in an upcoming release.

For now we must disable all copy operations until this issue is resolved.

**Comment by remram44** [comment]
An answer from the Anaconda team! I'm off buying a lottery ticket, but don't wait for me to check out conda/conda-env#60

**Comment by stephenakearns** [comment]
related to #119

**Comment by remram44** [comment]
Copying still gives a 500 error. Is anyone working on Anaconda at all?

**Comment by dsludwig** [comment]
@remram44 we have enabled `anaconda copy` again in our latest release (on January 20, version 2.14.1). The inline documentation on the linked page has been updated as well, but looking at it now, I see there is still a mistake - I will make sure this is fixed in the next release.
