### ISSUE TITLE
Copy anaconda packages temporarily out of service

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/docs.anaconda.org#119]
This will be back up and working in a future release

**Comment by dfroger** [comment]
Is copying the package by hand (ananconda upload ...) the best alternative for now?
Is there a way to presever package author name?

**Comment by jakirkham** [comment]
Could I propose a different solution than copying?

I think one of the challenges in the current ecosystem is that there are many useful packages from many people. This is, in fact, a good challenge. However, it raises the issue. What is the best way to get them from maintainers to end users? How many maintainers do we need for a type of package? Related, how many copies of a single package do we need? Do we even want to be copying them from one channel to another?

What if instead, we had a system where people could fork or alias useful packages from an author/channel they liked into their own channel. This avoid duplication of effort in producing these packages. Controls what packages can be retrieved from an upstream channel vs. which ones can't. Is virtually unnoticed by end users. Allows for updates to a package to be immediately available for end users.

Thoughts?

**Comment by Korijn** [comment]
Is there any progress on this at all?

**Comment by srossross** [comment]
Hi, @Korijn sorry for the delayed response. Yes, we hope to have copy back in the new year.

**Comment by ijstokes** [comment]
@Korijn we are actively working on an improved mechanism for package copying.  In the mean time, unfortunately, the functionality is not supported: we have disabled it server side, but left it in the client where (again, unfortunately) the error messages will not be very obvious as to why it isn't working.  We'll close this issue when everything is fixed.

**Comment by dsludwig** [comment]
We have re-enabled the `anaconda copy` command in the latest release (2.14.1, released yesterday). Thank you for your patience!
