### ISSUE TITLE
'Invalid dist_id' errors when uploading packages to binstar

### ISSUE THREAD

**Issue by jchodera** [Anaconda-Server/docs.anaconda.org#122]
We're seeing sporadic `Invalid dist_id` errors when attempting to upload packages to binstar:
```
TEST END: openmm-dev-7.0.0.dev0-py27_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/osx-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

+ binstar --quiet -t **** upload --force -u omnia miniconda/conda-bld/osx-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2
Using binstar api site https://api.anaconda.org
[warning] Distribution osx-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2 already exists ... removing 
[BinstarError] Invalid dist_id 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 434, in upload
    self._check_response(res)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 159, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'Invalid dist_id', 400)
```
These also have the undesirable effect of first deleting the remote package on binstar before attempting to upload, which leaves us without working packages on binstar.
Any ideas what might be causing this, or how to fix it?

**Comment by electronwill** [comment]
This is now in our bug tracker and we'll reply here with more information as soon as possible.

**Comment by hainm** [comment]
> These also have the undesirable effect of first deleting the remote package on binstar before attempting to upload, which leaves us without working packages on binstar.

I got the same problem when building C++ library. Just want to add my voice here and hopefully the problem will be solved soon.

**Comment by stephenakearns** [comment]
Short update - not easily reproduced in our environment. Short term: exploring adding additional logging info to better understand the error. Long-term solution: removing the need for the Dist_ID during upload process.

**Comment by jchodera** [comment]
Thanks for the update!

The worst part of this error behavior is that the binstar package is deleted *before* the failure, which causes removal of a potentially useful package from binstar.  This breaks lots of our travis builds that utilize these development packages.

**Comment by hainm** [comment]
@stephenakearns it happens with local build too.

```
$ binstar upload /home/haichit/anaconda3/conda-bld/linux-64/libcpptraj-dev-4.2.5-0.tar.bz2 --force
Using binstar api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file ambermd/libcpptraj-dev/4.2.5/linux-64/libcpptraj-dev-4.2.5-0.tar.bz2 ...
[warning] Distribution linux-64/libcpptraj-dev-4.2.5-0.tar.bz2 already exists ... removing
 uploaded 3084 of 3084Kb: 100.00% ETA: 0.0 minutes
[BinstarError] Invalid dist_id
```

I tried to upload again and it works. 
```
$ binstar upload /home/haichit/anaconda3/conda-bld/linux-64/libcpptraj-dev-4.2.5-0.tar.bz2 --force
Using binstar api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file ambermd/libcpptraj-dev/4.2.5/linux-64/libcpptraj-dev-4.2.5-0.tar.bz2 ...
 uploaded 3084 of 3084Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/ambermd/libcpptraj-dev

```

**Comment by hainm** [comment]
> Long-term solution: removing the need for the Dist_ID during upload process.

can you point me to the tutorial/doc about how to follow your comment here?

**Comment by jchodera** [comment]
Just an update that we're still seeing this issue sporadically.

Here's the traceback using the latest `anaconda-client`:
```
Using anaconda-server api site https://api.anaconda.org
[warning] Distribution linux-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2 already exists ... removing 
[BinstarError] Invalid dist_id 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 93, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 75, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/commands/upload.py", line 203, in main
    callback=upload_print_callback(args))
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/__init__.py", line 437, in upload
    self._check_response(res)
  File "/home/vagrant/miniconda/lib/python3.4/site-packages/binstar_client/__init__.py", line 161, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Invalid dist_id', 400)
```

**Comment by stephenakearns** [comment]
@srossross you were mentioning that this issue may have been resolved this week - is that right? if so, can you move it to "ready for review"?

**Comment by srossross** [comment]
We are going to release the new version in the new year. after the team gets back from vacation.

**Comment by jchodera** [comment]
We're not getting some new variants of this error when trying to upload from `travis-ci`:
```
Traceback (most recent call last):
  File "/anaconda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 206, in main
    callback=upload_print_callback(args))
  File "/anaconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 448, in upload
    self._check_response(res)
  File "/anaconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 164, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ("Invalid dist_id ObjectId('56a2456286ba914de33be032'), expected ObjectId('569fe16e122cf362bc41c9c8')", 400)
```
Any progress on even identifying what might be wrong or a potential workaround?

**Comment by jchodera** [comment]
Deleting the package from anaconda cloud seemed to fix this, at least for now.

**Comment by damianavila** [comment]
@stephenakearns Seeing this trying to upload packages manually on py27...

**Comment by stephenakearns** [comment]
@srossross - can we prioritize this issue this week? (revisit to confirm it's still occuring or resolved? It seems like it may still be reproducible according to @damianavila )

**Comment by srossross** [comment]
@dsludwig is this fixed on develop now?

**Comment by dsludwig** [comment]
Yup, this passes on my tests. On the next release, this issue will be fixed.

**Comment by jchodera** [comment]
Thanks!  Any idea when the next release will go live?

**Comment by dsludwig** [comment]
@jchodera we are going through our beta-testing process right now. A new release should go live some time this week - I will update this issue when that happens.

**Comment by hainm** [comment]
> @jchodera we are going through our beta-testing process right now. A new release should go live some time this week - I will update this issue when that happens.

would be greatly helpful update.

**Comment by stephenakearns** [comment]
@damianavila - I think you may have been experiencing this issue. Able to assist in Validating this fix in beta with @dsludwig ?

**Comment by damianavila** [comment]
Sure, I will add it to my todo list!

**Comment by dsludwig** [comment]
@jchodera @hainm the new release (2.15) is live! Please let me know if you still have this problem.

**Comment by hainm** [comment]
great. thanks.

**Comment by damianavila** [comment]
tested OK as well...
