### ISSUE TITLE
Update docs.anaconda.org/#UseCases

### ISSUE THREAD

**Issue by kerrywatson1** [Anaconda-Server/docs.anaconda.org#134]
You want to install conda packages
You want to install PyPI packages
More?

This page: http://docs.anaconda.org/#UseCases

@stephenakearns please reassign if needed.

**Comment by stephenakearns** [comment]
Hi @kerrywatson1 and @FirecatSue 

Other high-level use cases that can be added: 

- Publish/Share a notebook using integrated nbviewer
- Publish/Share a conda environment
- Build and distribute cross-platform conda packages (Organizations)
- Set up a 4 node cluster using Anaconda cluster as a sandbox for your hadoop development work
- Download free Optimization library (MKL)
- Academic Users: Download other free optimization libraries (can provide more detail here if needed)

I think we've discussed these already, but more detail woudl be helpful, LMK.
