### ISSUE TITLE
Draft new section Transfer packages from one channel to another 

### ISSUE THREAD

**Issue by kerrywatson1** [Anaconda-Server/docs.anaconda.org#137]
Currently unclear where to link this, but it needs to be drafted. 

From Flowdock:
[MichaelS: It’s in the package settings - click on the package, then click on the gears icon on the far right, click “admin” in the left menu, you’ll see a transfer button… a little buried, but it seems to work OK]

Seems like a user setting, so assigning to @FirecatSue 

Helper is @mistakevin

**Comment by srossross** [comment]
This will be fixed with #119
