### ISSUE TITLE
Update Anaconda Cloud FAQ

### ISSUE THREAD

**Issue by kerrywatson1** [Anaconda-Server/docs.anaconda.org#142]
Update http://docs.anaconda.org/faq.html

Start each section with "What is xyz?" and keep new user perspective. 

@electronwill can do Using the anaconda-client section and also give general help.

**Comment by kerrywatson1** [comment]
@stephenakearns for our meeting.

**Comment by stephenakearns** [comment]
Hi @electronwill can you make a small FAQ revision: 

Q. What kind of packages does Anaconda Cloud support?

A. Anaconda Cloud supports any type of package. Today, it's primarily used for conda and PyPI packages, as well as notebooks and environments.

after that, we can close this item.
