### ISSUE TITLE
BUG: Internal Server Error

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Server/docs.anaconda.org#144]
![screen shot 2015-10-22 at 15 22 36](https://cloud.githubusercontent.com/assets/3019665/10675938/dac9ce70-78d0-11e5-8e83-05b8675bdb24.png)

**Comment by jakirkham** [comment]
This not only affecting visiting the webpage, but it is affecting the downloading of packages from any channel.

**Comment by stephenakearns** [comment]
Thanks @jakirkham  -  we're aware of the issue. We are troubleshooting some underlying infrastructure issues that are affecting more than just Anaconda.org. @JeremyEnns will update when things are back to normal.

**Comment by jakirkham** [comment]
Thanks for the update, @stephenakearns.

**Comment by stephenakearns** [comment]
Hi @jakirkham - a little delayed, but earlier this afternoon (CDT timezone) Anaconda Cloud was back online. The root cause was identified and steps are being taken to prevent it from happening again in the future.  If you are still having issues, please let us know.

**Comment by jakirkham** [comment]
Thanks for the update. Seems to be working.

**Comment by jakirkham** [comment]
Something worth considering, it would be nice to have a status page ( https://status.io ) like Travis CI or others, which we could see performance and subscribe to updates.

**Comment by srossross** [comment]
Thanks for pointing that out. That is definitely worth looking into.
