### ISSUE TITLE
Update docs navigation, look & feel

### ISSUE THREAD

**Issue by FirecatSue** [Anaconda-Server/docs.anaconda.org#195]
Update the Anaconda Cloud documentation navigation and look and feel.

1. Address display hiccups and artifacts to extent possible, or LMK and I will add separate issues to be addressed later (see attached markups).
2. Add a Logo for Anaconda Cloud / Documentation (ensure it still links to docs.anaconda.org) (Victoria has them, I attached one; let's make sure they're approved)
3. Update CSS to use color scheme, fonts harmonizing with Anaconda Cloud.
4. Move Level 1 Headings (now in the top navigation) to the left sidebar, governing their subtopics. 
5. Update the "Go to Anaconda Cloud" to remove the Anaconda.org label :)

NOTE: @electronwill is updating the nav elements to remove some duplication of labels and changing order and hierarchy. I'm assigning this issue to him so he can notify @mistakevin when that work is complete. 

[Navigation - Cloud Docs.pdf](https://files.zenhub.io/56464ebc8294d8de6364d61a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by electronwill** [comment]
Looks very good!

Anaconda Cloud (anaconda.org) and docs.anaconda.org should both harmonize fonts colors and CSS with continuum.io's front page.

I'll reply when the content reorganization I'm working on goes through and we're ready for Kevin to work on the navigation bars.
