### ISSUE TITLE
Side-menu points to wrong content for Anaconda Build System

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/docs.anaconda.org#198]
What's the scoop with build documentation?  I went to anaconda.org then to "Help" then to "Building packages with Anaconda Cloud" which took me here: 

http://docs.anaconda.org/#BuildingPackagesWithAnacondaCloud

This does not tell me how to build packages with Anaconda Cloud at all.  It just tells me how to upload locally built packages.  What's the scoop?
That side-menu link should instead take me here: 

http://docs.anaconda.org/building.html

And the content here needs to be revised: it needs a different title and the text needs to clearly indicate that it is only describing how to upload locally built packages instead of suggesting that it will teach the reader how to do cross-platform builds remotely on Anaconda Build System.

Or just remove it entirely, since that material is probably covered elsewhere.

**Comment by electronwill** [comment]
You're right, that text does need to change. A more up to date draft of our overhaul of docs.anaconda.org is available at docs.anaconda.org/draft. As you can see there, there are various "fixme" sections and some blank headers in the "Managing Your Account" page, but we have changed the Quickstart section "Building packages with Anaconda Cloud" to "Build and upload packages" as well as moving it off the front page so it's more clear that it's just part of the Quickstart.
