### ISSUE TITLE
footer & top right link

### ISSUE THREAD

**Issue by electronwill** [Anaconda-Server/docs.anaconda.org#206]
1) top right link says Go to anaconda.org, change to Anaconda Cloud
2) footer links to this repo for issues, change to anaconda-server/support
3) footer says anaconda.org, change to Anaconda Cloud
4) footer Powered by Anaconda links to store.continuum.io, change to https://www.continuum.io/why-anaconda

@mistakevin @FirecatSue what else?

**Comment by FirecatSue** [comment]
Looks good, @electronwill

**Comment by electronwill** [comment]
Fixed by https://github.com/Anaconda-Server/docs.anaconda.org/pull/213 .
