### ISSUE TITLE
`anaconda copy` documentation is not present

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/docs.anaconda.org#218]
http://docs.anaconda.org/cli.html#Copy doesn't take you anywhere.

**Comment by FirecatSue** [comment]
Verified; there is no corresponding section for the Copy command argument's anchor link.

**Comment by stephenakearns** [comment]
quick note - moving this to the "channels epic"  - plan is to re-enable copy command in the next few weeks.

**Comment by dsludwig** [comment]
Added in https://github.com/Anaconda-Server/docs.anaconda.org/commit/5774ec0a4655de4bca5a7d28ee53f900876744a4
