### ISSUE TITLE
Improve Binstar docs and UX

### ISSUE THREAD

**Issue by chdoig** [Anaconda-Server/docs.anaconda.org#22]
Some issues to improve Binstar docs mentioned in internal mailing-list:

- [ ] Simplify examples (no need to write https://conda.binstar.org/)

- [ ] Make clear that conda install -c foo/channel/bar package installs latest version

- [ ] Make clear how to download from a dev channel

- [ ] Change docs to include the possibility of downloading version other than latest

- [ ] Inconsistent titles with downloaded package

- [ ] Inconsistent titles with package name

I'm including further explanation and quotes from the mailing list on each list item:

#### Simplify examples (no need to write https://conda.binstar.org/)
> I think it would also help a lot of the binstar examples all used

    conda install -c bokeh

> instead of

    conda install -c https://conda.binstar.org/bokeh

#### Make clear that conda install -c foo/channel/bar package installs latest version
 > We should definitely reiterate that, although note that if you just

    conda install -c bokeh/channel/dev bokeh

> it will pick the latest version

#### Make clear how to download from a dev channel 

You need to add "channel/dev" to the end of the URL
e.g.:
    conda install -c bokeh/channel/dev

#### Change docs to include the possibility of downloading version other than latest:

    conda install --channel https://conda.binstar.org/:REPOSITORY-PATH PACKAGE=VERSION

And include one example in the docs http://docs.binstar.org/conda.html#Install

#### Inconsistent titles with downloaded package

e.g:

![screen shot 2014-08-11 at 4 04 11 pm](https://cloud.githubusercontent.com/assets/4940549/3882835/19440190-219b-11e4-90f6-c8de75732c87.png)

Title says: bokeh / bokeh / 0.5.2.dev.20140808, but actually downloads 0.5.1.

#### Inconsistent title with package name

e.g:
bokeh 0.5.2+dev.20140808 in https://binstar.org/bokeh

**Comment by electronwill** [comment]
@chdoig are these all solved, or is there still more to do after #173 and #174 ?
