### ISSUE TITLE
Remove references to anaconda.yml from docs

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/docs.anaconda.org#220]
I thought I had reported this a few months ago, but I can't find a reference to it.  The documentation describes the option of an `anaconda.yml` file to define builds.  This is not supported in the current code base nor in any PR that I'm aware of (i.e. it isn't a matter of the docs leading the feature that is "soon to be released).

http://docs.anaconda.org/build.html

This is important because a new user should say/think "Why would I use `binstar.yml`? What is *binstar*?  I'll use `anaconda.yml` to configure my build." -- and then they'll try it and everything will appear broken.

IMO for sure `anaconda.yml` **should** be the name of the file and `binstar.yml` supported only "silently" for historical reasons until (perhaps) `anaconda.yml` evolves in a way that makes old `binstar.yml` files unsupported.  But AFAICT `anaconda.yml` is not supported at all, and I see no evidence that it is going to be supported any time soon, in which case the documentation should be updated to reflect present reality.

The move away from `binstar` is storied and documented here: https://github.com/Anaconda-Server/anaconda-server/issues/908

**Comment by ContinuumJira** [comment]
Hi Ian,
I'm a bit confused - i think the title of this should be "deprecate
filename "binstar.yml" in favour of "anaconda.yml"" - am I reading it rigjt?

On Wed, Dec 9, 2015 at 7:38 AM, Ian Stokes-Rees <notifications@github.com>
wrote:

> I thought I had reported this a few months ago, but I can't find a
> reference to it. The documentation describes the option of an anaconda.yml
> file to define builds. This is not supported in the current code base nor
> in any PR that I'm aware of (i.e. it isn't a matter of the docs leading the
> feature that is "soon to be released).
>
> http://docs.anaconda.org/build.html
>
> This is important because a new user should say/think "Why would I use
> binstar.yml? What is *binstar*? I'll use anaconda.yml to configure my
> build." -- and then they'll try it and everything will appear broken.
>
> IMO for sure anaconda.yml *should* be the name of the file and binstar.yml
> supported only "silently" for historical reasons until (perhaps)
> anaconda.yml evolves in a way that makes old binstar.yml files
> unsupported. But AFAICT anaconda.yml is not supported at all, and I see
> no evidence that it is going to be supported any time soon, in which case
> the documentation should be updated to reflect present reality.
>
> The move away from binstar is storied and documented here:
> Anaconda-Server/anaconda-server#908
> <https://github.com/Anaconda-Server/anaconda-server/issues/908>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/docs.anaconda.org/issues/220>.
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by goanpeca** [comment]
@stephenakearns  (BTW you appear as the Jira user)


---

I made the documentation changes to the build page and I included the reference to `anaconda.yml` cause I thought it was working like that at that point.

I submitted PR #221 to fix this.

Now, we need to open a separate issue in anaconda server (or anaconda build?) that deals with,  `Deprecate filename "binstar.yml" in favour of "anaconda.yml`
