### ISSUE TITLE
Better discussion of install_channels

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/docs.anaconda.org#231]
Whether users intend to add install channels to a build using something like:

```
install_channels:
 - javascript
 - r
 - some-other/c/dev
```
or 
```
conda config --add channels some-other/c/dev
```
, the docs need to point out that if a private channel is being added, then the full path to that channel must be specified, inclusive of the $TOKEN part used in authentication.

**Comment by dsludwig** [comment]
We could also accomplish this by allowing `anaconda-client` to read the API token from the environment variable `BINSTAR_API_TOKEN` (this is already set in the build script). This would allow `conda` to detect and use the API token when installing packages.

**Comment by postelrich** [comment]
I would think that a build should have access to other packages owned by the user/organization.

**Comment by PeterDSteinberg** [comment]
I think @dsludwig 's [PR](https://github.com/Anaconda-Server/anaconda-client/pull/269) addresses this issue.  I'll update the docs to mention tokens are interpolated to channels after that PR is merged.

**Comment by dsludwig** [comment]
We now explicitly call out in the documentation that if private packages are required, use a token URL.
