### ISSUE TITLE
document Anaconda repository gunicorn timeout option (for uploading large files?)

### ISSUE THREAD

**Issue by electronwill** [Anaconda-Server/docs.anaconda.org#243]
https://github.com/Anaconda-Server/anaconda-server/pull/883 added the optional argument '--timeout 120', where 120 can be any number of seconds. If --timeout is not used, the default value is 30. The docstring says this is the timeout threshold in seconds, and workers silent for more than this many seconds are killed and restarted.

@bkreider says just add this to the correct config file, which @mrduane says is probably binstar.yaml:
```
gunicorn:
    timeout: 120
```

As yet this is probably not clear enough to any member of the docs team to turn it into a docs pull request, so we'll need more clarification from Bradley (or Duane or someone else.) Is it correct that this option is used by adding lines such as those to the binstar.yaml file in Anaconda repo? What does it mean that workers silent for more than this many seconds are killed and restarted? What workers? Anaconda build workers? What does this have to do with uploading large files?

@npierotti is currently doing other work on Anaconda repository docs and may choose to include this in that project.

**Comment by bkreider** [comment]
@electronwill Thanks for creating this issue.  I don't know if that is the right syntax, but it looks right.  I've never used the option.

**Comment by electronwill** [comment]
@rafaelhbarros , can you help us explain to the users how to use --timeout?

**Comment by rafaelhbarros** [comment]
In a few words on my way to the car: it sets the maximum number of seconds
a request can last before it is forcefully killed. Think you're opening a
web page and it takes too long, you get tired of waiting and close it. The
server does that too, based on the timeout.

I can expand more tomorrow.

**Comment by electronwill** [comment]
Excellent-- thank you! We'll talk a bit more tomorrow to finish the details (role of workers, path of file to edit, correct syntax.)

**Comment by srossross** [comment]
@rafaelhbarros can you create a PR to add the new settings and defaults?

**Comment by electronwill** [comment]
OK, the documentation changes are live here. http://docs.continuum.io/anaconda-server/faq#how-can-i-stop-timeouts-when-uploading-large-files
