### ISSUE TITLE
Build Machine: before_script and after_script links are bad

### ISSUE THREAD

**Issue by tpowellcio** [Anaconda-Server/docs.anaconda.org#41]
http://localhost:8080/build/build_config.html
http://localhost:8080/build/build_config.html#before_script,after_script

Looks like they should have a space in the link after the ',' and before the word 'after' **#before_script, after_script**

![screen shot 2014-09-16 at 13 11 15](https://cloud.githubusercontent.com/assets/649601/4292391/ead79da0-3dcc-11e4-903c-f596daaa8843.png)

**Comment by electronwill** [comment]
Seems to be fixed, but please re-open this if I've made a mistake.
