### ISSUE TITLE
Failure to download package from organization non-standard channel 

### ISSUE THREAD

**Issue by ovz** [Anaconda-Server/docs.anaconda.org#54]
I have uploaded a private package to my organization, using non-standard channel test

The page 

https://binstar.org/organization/salford_systems/dashboard/channels/test

instructs to use the following command to install a package

conda install -c https://conda.binstar.org/salford_systems/channel/test package

Yet when I run it I get

[salford_wibu_test] C:\spm\git\demo\treenet_api_demo\test>conda install -c https
://conda.binstar.org/salford_systems/channel/test salford_wibu
Fetching package metadata: ....Error: Could not find Binstar user salford_system
s

I get the same error if I try to use a token

[salford_wibu_test] C:\spm\git\demo\treenet_api_demo\test>conda install -c https
://conda.binstar.org/t/<My Token here>/salford_systems/t
est package
Fetching package metadata: ...Error: Could not find Binstar user salford_systems

**Comment by ovz** [comment]
After I added the package to main channel I was able to use both command lines for Public and Private package. This confirms non-standard channel name is the trigger.

**Comment by electronwill** [comment]
Apologies for the slow response! Was this resolved?

**Comment by groutr** [comment]
I have a non-standard channel in my account and I can install with
`conda install -c <username>/channel/<channel name> <package(s)>`
