### ISSUE TITLE
trailing slash breaks links for "repodata"

### ISSUE THREAD

**Issue by openvest** [Anaconda-Server/docs.anaconda.org#59]
I don't think that the UX places a trailing slash, but it one is present (evil url hackers), the page "looks" ok but some links are broken (see the double slash in the attached screenshot)

This is pretty minor and is we never generate a trailing slash it is arguably OK to "not-fix" this "issue"
![binstar1](https://cloud.githubusercontent.com/assets/1633611/6007168/52a28450-aae6-11e4-8e3e-ab51064edd60.PNG)

**Comment by electronwill** [comment]
Confirmed that this problem is present by going to https://conda.anaconda.org/nsidc/ . Low priority but worth fixing on the site.

**Comment by electronwill** [comment]
It is a bug with the site and not the docs, so created a new issue there and will close this one:

https://github.com/Anaconda-Server/anaconda-server/issues/544
