### ISSUE TITLE
missing $ in $TOKEN in url reference

### ISSUE THREAD

**Issue by openvest** [Anaconda-Server/docs.anaconda.org#60]
![binstar3](https://cloud.githubusercontent.com/assets/1633611/6007459/30d14b98-aae8-11e4-9802-3ca9cf6c5e64.PNG)

**Comment by electronwill** [comment]
Confirmed. Will fix ASAP.

**Comment by electronwill** [comment]
Fixed in https://github.com/Anaconda-Server/anaconda-server/pull/568
