### ISSUE TITLE
'binstar remove' error message

### ISSUE THREAD

**Issue by jayvius** [Anaconda-Server/docs.anaconda.org#63]
Trying to remove a package from binstar using the remove command, but forgetting to prepend the username to the package name:

     binstar remove foo

produces an unhelpful error message:

    Using binstar api site https://api.binstar.org

**Comment by electronwill** [comment]
Apologies for the slow reply, Jay! Moved to the anaconda-server repo issues:

https://github.com/Anaconda-Server/anaconda-server/issues/543
