### ISSUE TITLE
Fix display of latest package available under channel tab.

### ISSUE THREAD

**Issue by flamingbear** [Anaconda-Server/docs.anaconda.org#64]
When looking at [channels](https://binstar.org/NSIDC/extended-generic-swath/channels) page, it shows that the latest version in the dev channel is 0.0.1dev9, but if you look under the [files](https://binstar.org/NSIDC/extended-generic-swath/files) tab you can see there are later build versions

The command line interface to install and upgrade **does** get the most recent build, but the interface shows dev9 as the latest release. So this looks like an interface problem only.

Thanks

![screen shot 2015-03-18 at 11 10 22 am](https://cloud.githubusercontent.com/assets/479480/6714768/b40ca856-cd5f-11e4-8331-b078f9cafc94.png)
![screen shot 2015-03-18 at 11 10 30 am](https://cloud.githubusercontent.com/assets/479480/6714772/b7bbdb84-cd5f-11e4-86ab-a681913d2f7c.png)

**Comment by electronwill** [comment]
Apologies for the slow response! Was this resolved? Currently extended-generic-swath seems gone, but https://anaconda.org/NSIDC/gsx/channels and the files tab there seem to be working correctly.

**Comment by flamingbear** [comment]
if you look at  
https://anaconda.org/NSIDC/nsidc0081/channels

You can see that the latest 'dev' package is : 1.2.0dev9	
and if you look at the dev channel. you can see there is a 1.2.0dev25  

So nope, this isn't fixed.  It's a website problem though, an install will get the correct package.

Please let me know when you've looked so that I can add the 1.2.1dev+ files back into the dev channel.

Thanks
Matt

**Comment by electronwill** [comment]
Understood and escalated. Thank you for helping me reproduce the bug!

**Comment by flamingbear** [comment]
I don't know how high priority I would consider it.  We're moving away from a dev number on our builds, so this won't affect us anymore.  But I thought you guys should see what was happening there.

Cheers,
Matt

**Comment by electronwill** [comment]
Yes, it's not the worst bug in anaconda.org I've seen, but we're definitely glad to know about it. Thank you for telling us.

**Comment by electronwill** [comment]
Closed here and created as a new anaconda-server issue: https://github.com/Anaconda-Server/anaconda-server/issues/545

**Comment by flamingbear** [comment]
Can I move my dev2 channel packages back to dev?  Or do you still need that example?

**Comment by electronwill** [comment]
You can go ahead and move them back to dev. Now that we're sure the bug is still there after all these months of changes since Mar 18, it should be pretty easy to reproduce it in one of our own repos.
