### ISSUE TITLE
Files list paginator for a package only shows two pages

### ISSUE THREAD

**Issue by krischer** [Anaconda-Server/docs.anaconda.org#67]
The paginator in the files list of a package, e.g.

https://binstar.org/obspy/obspy/files?page=1

only shows two pages, even though there are more packages.

It is possible to navigate to the third page by changing the URL to 

https://binstar.org/obspy/obspy/files?page=3

so this is just a UI issue.

![screen shot 2015-03-26 at 17 33 43](https://cloud.githubusercontent.com/assets/800487/6851263/4b02bfe6-d3de-11e4-9072-1dd304a1c580.png)

**Comment by electronwill** [comment]
Apologies for the slow reply! Moved to anaconda-server repo issues at https://github.com/Anaconda-Server/anaconda-server/issues/541
