### ISSUE TITLE
Document notebooks upload

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/docs.anaconda.org#68]

**Comment by stephenakearns** [comment]
Hi @malev - can you add a description here or close this item if it's not an issue?

**Comment by electronwill** [comment]
Does this mean that the docs should document how to upload a notebook, and they don't yet?

**Comment by goanpeca** [comment]
Isnt this covered by

http://docs.anaconda.org/cli.html#ManagingNotebooks  ?

**Comment by goanpeca** [comment]
Or the idea would be to add it to the [examples](http://docs.anaconda.org/examples.html) part?
