### ISSUE TITLE
package missing

### ISSUE THREAD

**Issue by openvest** [Anaconda-Server/docs.anaconda.org#70]
this is at the JPM AS install.
I've downloaded and used the teamcity-messages package here quite a number of times.  

It still shows up in the ui but clicking on it or attempting to download/install  via conda all result in a 404 error.  

![tc_messages_1](https://cloud.githubusercontent.com/assets/1633611/7301728/75de17b2-e9b2-11e4-8aa6-6741bff1e0f1.PNG)
![tc_messages_2](https://cloud.githubusercontent.com/assets/1633611/7301732/7b76a874-e9b2-11e4-8ff4-893075637ae2.PNG)

**Comment by electronwill** [comment]
Apologies for the delayed response! Was this resolved?
