### ISSUE TITLE
binstar confirm e-mail address has localhost as server in confirmation URL 

### ISSUE THREAD

**Issue by schadde** [Anaconda-Server/docs.anaconda.org#74]
This is the beginning text of the email I received to confirm my email in binstar:

"Thanks for signing up for binstar!

Please click the link below to confirm activation of your binstar account:

https://localhost:4990/account/confirm_email?...."

**Comment by seandavi** [comment]
Same here.

**Comment by cleme** [comment]
Yep, same issue

**Comment by dgonzo** [comment]
Probably related.

Got a confirmation email with this link:
"http://Magic/account/confirm_email?code=<code here>&email=<emailhere>"

**Comment by mathieu1** [comment]
Similar issue today:

Confirmation email link was `http://alpha.anaconda.org/account/confirm_email?...`, which lead to a 404 error page.
Removing `alpha.` in the link worked.

**Comment by electronwill** [comment]
This seems to be a problem with the software and not the docs, and already documented here: https://github.com/Anaconda-Server/anaconda-server/issues/325

I'm closing this one, but if I've misunderstood, please just go ahead and re-open it.
