### ISSUE TITLE
*NO* healthy workers

### ISSUE THREAD

**Issue by kalefranz** [Anaconda-Server/docs.anaconda.org#76]
https://binstar.org/kalefranz/nginx/builds/16/0

Build 16.0 Sumitted id:556cdce43273af6fdb97525c
There are *NO* healthy workers accepting jobs for the queue build/binstar/public. Your build was not submitted

**Comment by moble** [comment]
+1

**Comment by mutirri** [comment]
On Friday build workers were down for maintenance purposes.
However right now, both linux64 machines from build/binstar/public queue are up and ready to serve.
