### ISSUE TITLE
Binstar build docs - out of date old content

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Server/docs.anaconda.org#78]
From Antoine (not sure of his github name)
```
I searched for "binstar.yml" on Google (looking for binstar build docs)
and I got two almost similar URLs as result:
http://docs.binstar.org/build-config.html
http://docs.binstar.org/build_config.html

Those two seem to correspond to different versions of the docs. Which
one is the most recent? :-) The older one should probably be removed, to
avoid confusion...

Regards

Antoine.
```

**Comment by pitrou** [comment]
(that was me)

**Comment by electronwill** [comment]
Seems to be fixed now:

http://docs.binstar.org/build_config.html : redirect to http://docs.binstar.org/build-config.html
http://docs.binstar.org/build-config.html : correct page
http://docs.anaconda.org/build_config.html : 404
http://docs.anaconda.org/build-config.html : correct page
