### ISSUE TITLE
missing 404 page

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Server/docs.anaconda.org#80]
we have a nasty 404 page, because error.html, doesn't exist.  The missing key is error.html.

![screen shot 2015-06-10 at 2 27 32 pm](https://cloud.githubusercontent.com/assets/1699478/8090567/d1dd9caa-0f7c-11e5-962d-b1b2bf62930a.png)

If you have a different error page, you can change the setting here in the AWS console for S3:
![screen shot 2015-06-10 at 2 28 26 pm](https://cloud.githubusercontent.com/assets/1699478/8090607/03053ffe-0f7d-11e5-8f6f-765ad8e18f44.png)

**Comment by electronwill** [comment]
Should the docs.anaconda.org 404 page be about the same as the one for anaconda.org?

https://anaconda.org/foo

**Comment by bkreider** [comment]
Please no.  I can't stand that 404. ;)

**Comment by electronwill** [comment]
Hah! Yeah, I've been hit with it enough times not to like it much either.

More specific question: Should the docs 404 have any information that the anaconda.org 404 does not? It seems that the anaconda.org 404 shows the anaconda.org header and footer, and if the docs 404 has the header with the "FAQ" link and the footer with the "Report an issue" link, I think that should be enough, but want to be sure you don't have other info in mind.

**Comment by bkreider** [comment]
I'm the last person to really answer the web design questions.  My main problem was just that we don't have any 404 error.html defined, so people get the ugly S3 error instead.

**Comment by electronwill** [comment]
OK, I'll just work on getting error.html defined for now, and if anyone wants to add more info later we can handle it then.

**Comment by electronwill** [comment]
moved to https://continuumproductteam.atlassian.net/browse/AS-714
