### ISSUE TITLE
Can't "get started" -- authorization error

### ISSUE THREAD

**Issue by drf5n** [Anaconda-Server/docs.anaconda.org#81]
Following the getting started docs at http://docs.binstar.org/  I got:

    $ conda install -c binstar binstar
    Fetching package metadata: ....Error: HTTPError: 401 Client Error: UNAUTHORIZED: https://conda.binstar.org/binstar/noarch/

I appear to have a binstar installed:

    $ binstar --version
    binstar Command line client (version 0.10.1)
    $ binstar login
    Using binstar api site https://api.binstar.org
    Username: drf5n
    drf5n's Password: 
    [error] It appears you are already logged in from host v21837.local 
    [error] Logging in again will remove the previous token. 
    [error] Otherwise you can login again and specify a different hostname with "--hostname"  
    Would you like to continue [Y|n]: y
    drf5n's login successful
    $ binstar whoami
    Using binstar api site https://api.binstar.org
    Anonymous User
    $ binstar logout
    Using binstar api site https://api.binstar.org
    The action you are performing requires authentication, please sign in:
    Using binstar api site https://api.binstar.org
    Username: drf5n
    drf5n's Password: 
    [error] It appears you are already logged in from host v21837.local 
    [error] Logging in again will remove the previous token. 
    [error] Otherwise you can login again and specify a different hostname with "--hostname" 
    Would you like to continue [Y|n]: y
    drf5n's login successful
    Using binstar api site https://api.binstar.org 
    [Unauthorized] This domain requires token authentication 
    $ binstar whoami
    Using binstar api site https://api.binstar.org
    Anonymous User

Suggestions?

**Comment by drf5n** [comment]
So I now understand that "Logging in again will remove the previous token." means that it will replace the previous token on the server.  I saw this by watching the date and ID on my https://binstar.org/settings/access page before and after a cycle of logging in.

My user name on my local machine (drf) is different than my account on binstar (drf5n)  Could this be an issue?

**Comment by malev** [comment]
@drf5n I think we need to update that piece of documentation.
FWI, we renamed `binstar` into `anaconda-client` so could you try:
```
conda install anaconda-client
anaconda --help
```
If that works, you can use `anaconda` in replace to binstar.

**Comment by drf5n** [comment]
I'm not sure it fixes my problem:

    531 [drf@v21837 ~]$ anaconda login
    Using binstar api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    [warning] It appears you are already logged in from host v21837 
    [warning] Logging in again will remove the previous token.  (This could cause troubles with virtual machines with the same hostname) 
    [warning] Otherwise you can login again and specify a different hostname with "--hostname" 
    Would you like to continue [Y|n]: 
    drf5n's login successful
    532 [drf@v21837 ~]$ anaconda whoami
    Using binstar api site https://api.anaconda.org
    Anonymous User
    533 [drf@v21837 ~]$ 

I `conda remove binstar` and `conda install anaconda-client` then `anaconda --help` works, but it appears not to know me as drf5n.  For example:

    538 [drf@v21837 ~]$ anaconda  search -t conda anaconda
    Using binstar api site https://api.anaconda.org
    Run 'anaconda show <USER/PACKAGE>' to get more details:
    The action you are performing requires authentication, please sign in:
    Using binstar api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    [warning] It appears you are already logged in from host v21837 
    [warning] Logging in again will remove the previous token.  (This could cause troubles with virtual machines with the same hostname) 
    [warning] Otherwise you can login again and specify a different hostname with "--hostname" 
    Would you like to continue [Y|n]: y
    drf5n's login successful
    Using binstar api site https://api.anaconda.org
    Run 'anaconda show <USER/PACKAGE>' to get more details:
    [Unauthorized] This domain requires token authentication
