### ISSUE TITLE
Unclear where to report issues

### ISSUE THREAD

**Issue by ahmadia** [Anaconda-Server/docs.anaconda.org#87]
The Anaconda Server documentation (hosted by this repository) links back here to "Report an issue" when reading the documentation.  Otherwise, there's no clear lines of communication for requesting help or reporting issues in the server itself.

**Comment by malev** [comment]
Agree! Thanks for the suggestion

**Comment by electronwill** [comment]
Good point. It makes sense for the docs to link to https://github.com/Anaconda-Server/docs.anaconda.org/issues to report bugs in the docs. For bugs in Anaconda Server there is https://github.com/Anaconda-Server/anaconda-server/issues but that's a private repo. https://github.com/Anaconda-Server/anaconda-client/issues is public, and maybe that's the best choice.

**Comment by malev** [comment]
@electronwill because `conda-env` lives at the anaconda's repo: http://repo.continuum.io/pkgs/free/osx-64/

**Comment by stephenakearns** [comment]
@ahmadia @malev @electronwill  - if you are logged into Anaconda.org...

1. Footer: "report an issue" links to this repo
2. Footer: "contact us" links to a sales page on continuum.io (don't love this)
3. Plans and Pricing page: has a "contact us" link which is a mailto:support@Anaconda.org which is an alias for support@continuum.io which reaches the @JeremyEnns and the support team. 

My proposal:
1. All "contact us" links on Anaconda.org should point to the same thing
2. There should be a proper "contact us" page on Anaconda.org which outlines the appropriate options

Options should probably include: 
- Report an issue (docs or functionality) --> docs.anaconda.org repo 
- Contact Sales

@JeremyEnns are there any scenarios where Anaconda.org users should be emailing support@continuum.io?

**Comment by electronwill** [comment]
From Flowdock today:

Sean 14:50
@team @StephenK and I were talking. we are going to eventually shut down the issue pages on anaconda-server/anaconda-client, anaconda-server/anaconda-build and anaconda-server/deploy
We are going to use anaconda-server/anaconda-server for internal issues
and anaconda-server/docs.anaconda.org to let public customers report issues.

**Comment by stephenakearns** [comment]
Do you want me to create an Issue to track "Create 'Contact Us' page"

On Tue, Jul 28, 2015 at 4:07 PM, Marcos Vanetta <notifications@github.com>
wrote:

> Agree! Thanks for the suggestion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/docs.anaconda.org/issues/87#issuecomment-125754041>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

**Comment by electronwill** [comment]
https://continuumproductteam.atlassian.net/browse/AS-715
