### ISSUE TITLE
Outdated "Please install binstar using pip"

### ISSUE THREAD

**Issue by dalcinl** [Anaconda-Server/docs.anaconda.org#92]
http://docs.anaconda.org/examples.html#InstallingTheBinstarCommand
I've been using binstar and binstar-build from conda with no problems for months.

BTW, I would suggest to mention first the "To install binstar with conda" instructions.

**Comment by malev** [comment]
@dalcinl thanks for reporting.
If you take a look at this https://github.com/Anaconda-Server/docs.anaconda.org/commit/14470c3ab6b4b67172835dfa18df29c949b0ed4c you will see that the update is soon to be released.
