### ISSUE TITLE
Broken links on anaconda.org/dashboard

### ISSUE THREAD

**Issue by tdhopper** [Anaconda-Server/docs.anaconda.org#94]
When I'm logged in to https://anaconda.org/dashboard there is this text:

```
anaconda.org allows you to create or distribute software packages.
Getting started: Installing your first package
Getting started: Distributing your first package
```

The installing and distributing links are both broken.

**Comment by malev** [comment]
Thanks for reporting!

**Comment by Maggie-M** [comment]
@malev I noticed there's another broken install link on the description page of a given package (*https://anaconda.org/channel/package*)

![screen shot 2015-08-24 at 10 56 30 am](https://cloud.githubusercontent.com/assets/1417520/9445006/69cfeb32-4a4f-11e5-9fdf-d34c481fefc7.png)

If you click that link, you're taken to this page, http://docs.anaconda.org/conda.html#Install , which returns a 404.

**Comment by electronwill** [comment]
confirmed-- http://docs.binstar.org/conda.html#Install works, http://docs.anaconda.org/conda.html#Install 404s
