### ISSUE TITLE
comment on: library issues with cdo and nco

### ISSUE THREAD

**Issue by CloLanglais** [Anaconda-Server/docs.anaconda.org#98]
Hi,

I finally solved my problem, but just wanted to let people know that the packages needs to be changed for nco and cdo.

I just reinstalled anaconda on OS X
installed nco
$conda install -c https://conda.binstar.org/ioos nco
installed cdo
$conda install -c https://conda.binstar.org/birdhouse cdo

I have a library issue when using nco and cdo
"dyld: Library not loaded: @rpath/libhdf5_hl.9.dylib"
looking in anaconda/lib , libhdf5_hl.10.dylib has been build, not libhdf5_hl.9.dylib
package hdf5-1.8.15.1 has been downloaded/updated when installing nco

I installed  an older version of hdf5  to get libhdf5_hl.9.dylib
$conda install -f hdf5-1.8.14-0.tar.bz2 (downloaded on https://conda.binstar.org/)

now cdo is working! yeah!
 but nco has still issues with another lib : libgsl.0.dylib

gsl was not identified as a missing package when installing nco
I installed gsl:
$conda install -c https://conda.binstar.org/asmeurer gsl
now everything is working

hope that this might help others!
and maybe the conda packages should be updated.

cheers

**Comment by malev** [comment]
@CloLanglais can you please move this question to the [anaconda mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/anaconda)
