### ISSUE TITLE
Can't create groups in an organization

### ISSUE THREAD

**Issue by mcg1969** [Anaconda-Server/docs.anaconda.org#99]
I've created a new organization ("Gurobi") and whenever I try to create a group within that organization, it rejects every single choice I try: "Users", "Contributors", etc.

**Comment by srossross** [comment]
Thanks, try only ascii lower case. I'll fix/improve this for next release

**Comment by mcg1969** [comment]
Yes, that works.

**Comment by malev** [comment]
Moving this to a proper repo
